fix own glaring mistakes

diff --git a/share/spack/qa/run-clingo-py2-bootstrap b/share/spack/qa/run-clingo-py2-bootstrap
--- a/share/spack/qa/run-clingo-py2-bootstrap
+++ b/share/spack/qa/run-clingo-py2-bootstrap
@@ -14,6 +14,12 @@
 #     run-clingo-py2-bootstrap
 #
 
+# TODO(#20123): there are multiple alternatives to this script:
+#  - TODO(#20430): package spack as a PEX file to avoid mixing up spack-installed packages
+#                  and others!
+#  - TODO(#20260): sandbox all builds with fakechroot to avoid this double bootstrapping!
+# - Add your own! #20207 makes python configuration a lot smarter, and yet still fails CentOS 6.
+
 ORIGINAL_PATH="$PATH"
 
 . "$(dirname $0)/setup.sh"
@@ -36,26 +42,36 @@ if ! python --version 2>&1 | grep -F 2.6; then
 fi
 
 # Game plan: install the same python, with a much less broken installation
-# (headers and libraries where clingo can find them). But first, we'll need to
-# install yet another python, then work our way back.
+# (headers and libraries where clingo can find them).
 
-# (~dbm~pyexpat is necessary to build python 2 in this environment.)
+# TODO: thanks to a quirk of CentOS 6 (and maybe others), it *does* contain libpython in /usr/lib64.
+# However, all but one of the necessary python-dev header files are missing by default, and
+# even that libpython library is somehow corrupt, causing any attempt to install another python
+# interpreter of the same version to fail at install time.
+
+# Note that installing, and then requiring the user to use an interpreter with a different version,
+# may break a lot of 2.6-only code. So to avoid changing the python version for the user by
+# accident, we actually need to install *yet another* python whose libpython doesn't clash with the
+# OS python, then work our way back to the python we want.
+
+# '~dbm~pyexpat' is necessary to build python 2.7 in specifically this environment. To be clear,
+# in most other environments, using '+dbm+pyexpat' is necessary to build.
 spack install 'python@2.7.18~dbm~pyexpat+shared'
 
 # Many other libraries will fail to build correctly when we load this new gcc
-# unless we enable +binutils.
+# unless we also enable +binutils.
 spack install --verbose --fail-fast -y -n -j 6 'gcc@10.2.0+binutils'
 
 # Load the newer python to avoid having this build fail while looking for the
 # broken centos6 python library in /usr/lib64.
-# TODO: sandbox all builds with fakechroot to avoid this double bootstrapping!
 spack load 'python@2.7.18~dbm~pyexpat+shared'
-# Install the same python again, this time ready to build modules against.
+# Install the same python again, this time ready to build modules against (with normal headers and
+# libpython).
 spack install "python@$(cat python-full-version.txt)~dbm~pyexpat+shared"
-# Our python is now the same again, but with a reasonable header and shared
+# Our python is now the same (version) again, but with a reasonable header and shared
 # library arrangement!
 spack load "python@$(cat python-full-version.txt)~dbm~pyexpat+shared"
-# Ensure spack has registered the built gcc as a compiler.
+# Ensure spack has registered the built gcc as a compiler (this should error if not).
 spack compiler find
 # Build clingo.
 spack install --verbose --fail-fast -y -n 'clingo@spack+python%gcc@10.2.0'
@@ -63,8 +79,8 @@ spack install --verbose --fail-fast -y -n 'clingo@spack+python%gcc@10.2.0'
 # For fun, make it run a solve on the same spec.
 spack solve 'clingo@spack+python'
 if spack spec 'clingo@spack+python'; then
-  echo 1>&2 UNEXPECTED FAILURE: spack spec should have failed
+  echo 1>&2 'UNEXPECTED FAILURE: spack spec should have failed!'
   exit 1
 else
-  echo 1>&2 EXPECTED FAILURE: spack spec uses the v1 concretizer.
+  echo 1>&2 'EXPECTED FAILURE: spack spec uses the v1 concretizer!'
 fi
