zsh before bash

diff --git a/share/spack/qa/run-unit-tests b/share/spack/qa/run-unit-tests
--- a/share/spack/qa/run-unit-tests
+++ b/share/spack/qa/run-unit-tests
@@ -77,8 +77,8 @@ echo "exit code: $?"
 #bash "$QA_DIR/completion-test.sh"
 #echo "exit code: $?"
 
-bash "$QA_DIR/test.sh"
-echo "exit code: $?"
+#bash "$QA_DIR/test.sh"
+#echo "exit code: $?"
 zsh "$QA_DIR/test.sh"
 echo "exit code: $?"
 dash "$QA_DIR/test.sh"
