fix multiple issues with the docker images
 - fixed an issue where some undesirable parts of
   the spack source tree were being copied into
   the image context.

 - added a workaround for a tty ioctl warning on
   ubuntu

 - adjusted how the main images are built so that
   `RUN spack ...` works automatically for child
   images that base themselves on them.

diff --git a/share/spack/docker/Dockerfile b/share/spack/docker/Dockerfile
--- a/share/spack/docker/Dockerfile
+++ b/share/spack/docker/Dockerfile
@@ -13,6 +13,7 @@ ENV DOCKERFILE_BASE=$BASE                     \
     SPACK_ROOT=/spack                         \
     FORCE_UNSAFE_CONFIGURE=1                  \
     DEBIAN_FRONTEND=noninteractive            \
+    CURRENTLY_BUILDING_DOCKER_IMAGE=1         \
     container=docker
 
 COPY bin   $SPACK_ROOT/bin
@@ -110,7 +111,10 @@ RUN rm -rf $SPACK_ROOT/.git                                          \
  && pip install boto3                                                \
  && (  echo ". /usr/share/lmod/lmod/init/bash"                       \
     && echo ". $SPACK_ROOT/share/spack/setup-env.sh"                 \
-    && echo ". $SPACK_ROOT/share/spack/spack-completion.bash" )      \
+    && echo "if [ \"\$CURRENTLY_BUILDING_DOCKER_IMAGE\" '!=' '1' ]"  \
+    && echo "then"                                                   \
+    && echo "  . $SPACK_ROOT/share/spack/spack-completion.bash"      \
+    && echo "fi"                                                   ) \
         >> /etc/profile.d/spack.sh                                   \
  && ln -s $SPACK_ROOT/share/spack/docker/handle-ssh.sh               \
         /etc/profile.d/handle-ssh.sh                                 \
@@ -126,7 +130,15 @@ MASK [[ $DISTRO_VERSION =~ (centos|fedora|opensuse|rhel.*) ]]
 RUN rm -f /run/nologin
 MASK POP
 
+# [WORKAROUND]
+# https://superuser.com/questions/1241548/
+#     xubuntu-16-04-ttyname-failed-inappropriate-ioctl-for-device#1253889
+RUN [ -f ~/.profile ]                                                   \
+ && sed -i 's/mesg \\-n/( tty -s \\&\\& mesg -n || true )/g' ~/.profile \
+ || true
+
 WORKDIR /root
-ENTRYPOINT ["bash", "/spack/share/spack/docker/entrypoint.bash"]
+SHELL ["/bin/bash", "-l", "-c"]
+ENTRYPOINT ["/bin/bash", "/spack/share/spack/docker/entrypoint.bash"]
 CMD ["docker-shell"]
 
