bootstrap.yml: reduce runtime
Signed-off-by: Harmen Stoppels <me@harmenstoppels.nl>

diff --git a/.github/workflows/bootstrap.yml b/.github/workflows/bootstrap.yml
--- a/.github/workflows/bootstrap.yml
+++ b/.github/workflows/bootstrap.yml
@@ -140,24 +140,18 @@ jobs:
       - name: Bootstrap clingo
         run: |
           set -e
+          . share/spack/setup-env.sh
+          spack bootstrap disable github-actions-v0.6
+          spack bootstrap disable spack-install
           for ver in 3.8 3.9 3.10 3.11 3.12 3.13 3.14; do
-            not_found=1
-            ver_dir="$(find $RUNNER_TOOL_CACHE/Python -wholename "*/${ver}.*/*/bin" | grep . || true)"
-            if [[ -d "$ver_dir" ]] ; then
-              echo "Testing $ver_dir"
-              if $ver_dir/python --version ; then
-                export PYTHON="$ver_dir/python"
-                not_found=0
-                old_path="$PATH"
-                export PATH="$ver_dir:$PATH"
-                ./bin/spack-tmpconfig -b ./.github/workflows/bin/bootstrap-test.sh
-                export PATH="$old_path"
-              fi
-            fi
-            if (($not_found)) ; then
-              echo Required python version $ver not found in runner!
+            ver_dir="$(find "$RUNNER_TOOL_CACHE/Python" -wholename "*/${ver}.*/*/bin" | grep . || true)"
+            export SPACK_PYTHON="$ver_dir/python3"
+            if [ ! -d "$ver_dir" ] || ! "$SPACK_PYTHON" --version; then
+              echo "Python $ver not found"
               exit 1
             fi
+            spack solve zlib
+            tree ~/.spack/bootstrap/store
           done
       - name: Bootstrap GnuPG
         run: |
